# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: (^backend/src/examples/data/|^backend/src/tests|^terraform/secrets)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        entry: "black backend --config backend/pyproject.toml --target-version py310"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=backend/.flake8"]
        additional_dependencies:
          - "flake8-eradicate"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic"
          - "sqlalchemy"
          - "pytest"
          - "fastapi"
        entry: "mypy --config-file backend/pyproject.toml"
        exclude: ^backend/src/database/migrations/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        exclude: "^(backend|frontend/node_modules)"
        args: ["-w"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.16.0"
    hooks:
      - id: eslint
        types: [file]
        types_or: [ts, javascript, vue]
        additional_dependencies:
          - "eslint-plugin-simple-import-sort@8.0.0"
          - "eslint@8.22.0"
          - "eslint-plugin-prettier@5.0.0"
          - "eslint-plugin-vue@9.3.0"
          - "eslint-config-prettier@8.3.0"
          - "@vue/eslint-config-typescript@11.0.0"
        exclude: "^(backend|frontend/node_modules)"
        args:
          - "--fix"
          - "--ignore-path frontend/.eslintignore"
