version: "3.8"

services:
  database:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=engage
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=engage
    ports:
      - 5432:5432
    networks:
      - engage2

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - CSRF_SECRET=3b0c0af2b9f2e717ee9bf91a
      - POSTGRES_USER=engage
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=engage
    ports:
      - 8000:8000
      - 5678:5678
      - 5679:5679
    command: ["python", "main.py"]
    networks:
      - engage2
    volumes:
      - ./backend/src:/app

networks:
  engage2: