"""Insert legal forms and sectors

Revision ID: 0002
Revises: 0001
Create Date: 2023-07-23 17:41:30.774603

"""
import sqlalchemy as sa
from alembic import op
from models import LegalForm, Sector

LEGAL_FORMS = [
    "e.V. - Eingetragener Verein",
    "gGmbH - Gemeinnützige Gesellschaft mit beschränkter Haftung",
    "GmbH - Gesellschaft mit beschränkter Haftung",
    "gUG - Gemeinnützige Unternehmergesellschaft",
    "UG - Unternehmergesellschaft",
    "Stiftung",
]

SECTORS = [
    "Bildung",
    "Gesundheit",
    "Kultur",
    "Sport",
    "Umwelt",
]


# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        table=Sector.__table__,
        rows=[{"name": sector} for sector in SECTORS],
    )
    op.bulk_insert(
        table=LegalForm.__table__,
        rows=[{"name": legal_form} for legal_form in LEGAL_FORMS],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(Sector).where(Sector.name.in_(SECTORS)))
    op.execute(sa.delete(LegalForm).where(LegalForm.name.in_(LEGAL_FORMS)))
    # ### end Alembic commands ###
